apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-service
spec:
  replicas: {{ .Values.payroll.replicaCount }}
  selector:
    matchLabels:
      app: payroll-service
  template:
    metadata:
      labels:
        app: payroll-service
    spec:
      containers:
        - name: payroll-service
          image: "{{ .Values.payroll.image }}"
          ports:
            - containerPort: {{ .Values.payroll.port }}