spring.application.name=employee-management-application
# JPA
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# H2 Database
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/employeedb
spring.datasource.username=embarkx
spring.datasource.password=embarkx
spring.jpa.database=POSTGRESQL
#spring.datasource.url=postgresql://postgres:VIFwhjoObYvOirvdcHxZcMbgTIzSoQba@postgres.railway.internal:5432/railway
#server.port=${PORT:8080}
#spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
#spring.datasource.username=postgres
#spring.datasource.password=VIFwhjoObYvOirvdcHxZcMbgTIzSoQba
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#aws s3
aws.s3.bucket-name=emp-mng-data
aws.s3.region= us-east-2

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=employee-s3-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.topic.employee-events=employee-events


