apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-service.fullname" . }}
  labels:
    {{- include "employee-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "employee-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "employee-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: employee-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}