apiVersion: v2
name: employee-management-system
description: Umbrella chart for Employee Management microservices
type: application

version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: employee-service
    version: "0.1.0"
    repository: "file://../employee-service"

  - name: payroll-service
    version: "0.1.0"
    repository: "file://../payroll-service"